//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllowanceType
    {
        public int All_Id { get; set; }
        public string All_Type { get; set; }
        public Nullable<double> All_Perc { get; set; }
        public Nullable<double> Salary { get; set; }
    }
}
