//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int Att_Id { get; set; }
        public string RFID_Id { get; set; }
        public Nullable<System.DateTime> Att_In { get; set; }
        public Nullable<System.DateTime> Att_Out { get; set; }
        public Nullable<System.DateTime> Att_Date { get; set; }
    }
}
