//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonofied
    {
        public int BonofieId { get; set; }
        public string Gr_No { get; set; }
        public Nullable<int> Class_Id { get; set; }
        public Nullable<System.DateTime> Date_Of_Generation { get; set; }
    }
}
