//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveType
    {
        public int Ltype_Id { get; set; }
        public string L_Name { get; set; }
        public Nullable<int> No_Leave { get; set; }
    }
}
