//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReciptDetail
    {
        public int Reciept_id { get; set; }
        public string RecieptFor { get; set; }
        public string RecieptFrom { get; set; }
        public Nullable<int> Amt { get; set; }
        public Nullable<System.DateTime> Rec_Date { get; set; }
        public string P_Mode { get; set; }
        public string Reference { get; set; }
    }
}
