//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int Staffid { get; set; }
        public Nullable<int> StaffTypeid { get; set; }
        public string FNname { get; set; }
        public string Mname { get; set; }
        public string Lname { get; set; }
        public string Cno1 { get; set; }
        public string Cno2 { get; set; }
        public string Address { get; set; }
        public Nullable<int> Cityid { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public Nullable<System.DateTime> Doj { get; set; }
        public string Gender { get; set; }
        public string Cast { get; set; }
        public string Nationality { get; set; }
        public string Religion { get; set; }
        public string Spouse { get; set; }
        public string AdhaarNo { get; set; }
        public string BankName { get; set; }
        public string IFSCcode { get; set; }
        public string BankAccountno { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<double> Salary { get; set; }
        public string Rfid { get; set; }
        public string Email { get; set; }
        public string yearsOfExperience { get; set; }
        public string Qualification { get; set; }
    }
}
