//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Stud_Id { get; set; }
        public string General_Regis_No { get; set; }
        public Nullable<System.DateTime> Date_Of_Addmission { get; set; }
        public string Student_Name { get; set; }
        public string Father_Name { get; set; }
        public string Mother_Name { get; set; }
        public string Father_Occupation { get; set; }
        public string Mother_Occupation { get; set; }
        public string Guardian_Name { get; set; }
        public string Cast { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string Religion { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> Classid { get; set; }
        public Nullable<int> Divid { get; set; }
        public string Previous_School_Name { get; set; }
        public string Phone_No { get; set; }
        public string HomePhoneNo { get; set; }
        public string Address { get; set; }
        public Nullable<int> City_Id { get; set; }
        public Nullable<int> State_Id { get; set; }
        public Nullable<int> Country_Id { get; set; }
        public byte[] Photo { get; set; }
        public string AadhaarNo { get; set; }
    }
}
