//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionAllowance
    {
        public int All_TransId { get; set; }
        public Nullable<int> All_Id { get; set; }
        public Nullable<int> Staff_Id { get; set; }
        public Nullable<System.DateTime> F_Date { get; set; }
        public Nullable<System.DateTime> T_Date { get; set; }
        public Nullable<System.DateTime> Entry_Date { get; set; }
        public Nullable<double> Amt { get; set; }
    }
}
